image: alpine:3

stages:
  - dev

before_script:
  - apk update
  - apk add bash
  - apk add file
  - apk add gcc
  - apk add make
  - apk add musl-dev

test:
  stage: dev
  script:
    - bash dev.sh
