.TH DICE "1" "May 2020" "dice version 1.0, (c) 2020 XGQT" "User Commands"
.SH NAME
dice \- rolls some dice
.SH SYNOPSIS
.B dice
[\fI\,OPTION\/\fR]... [\fI\,NUMBER\/\fR]
.SH DESCRIPTION
Rolls some dice.
.SH OPTIONS
.TP
\fB\-h\fR
Print short help
.TP
\fB\-\-help\fR
Print long help
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version number
.TP
\fB\-s\fR, \fB\-\-small\fR
Roll small dice
.TP
\fB\-0\fR, \fB\-\-none\fR
Only generate numbers
.PP
.SH "SEE ALSO"
Bugs: <https://gitlab.com/xgqt/dice/>
.br
Home: <https://gitlab.com/xgqt/dice/>
.br
Copyright (c) 2020, XGQT
.br
Licensed under the GNU GPL v3 license
